# Generated by Django 4.1.4 on 2023-01-02 15:06

import atila.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=atila.utils.random_string, max_length=128, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('segments', models.JSONField(blank=True, default=atila.utils.ModelUtils.empty_list, null=True)),
                ('image', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
