# Generated by Django 4.1.4 on 2023-01-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='transcription_source',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
