# Generated by Django 4.1.4 on 2023-02-12 18:45

import atila.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0002_document_transcription_source_document_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summaries',
            field=models.JSONField(blank=True, default=atila.utils.ModelUtils.empty_list, null=True),
        ),
    ]
