# Generated by Django 4.1.4 on 2024-11-18 16:21

import atila.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_remove_userprofile_atlas_searches_and_more'),
        ('atlas', '0003_document_summaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditsCode',
            fields=[
                ('id', models.CharField(default=atila.utils.random_string, max_length=32, primary_key=True, serialize=False)),
                ('code', models.CharField(default=atila.utils.random_string, max_length=32, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('used_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.userprofile')),
            ],
        ),
    ]
