# Generated by Django 4.1.4 on 2024-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0004_creditscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditscode',
            name='atlas_credits',
            field=models.IntegerField(default=0),
        ),
    ]
