# Generated by Django 4.1.4 on 2025-02-17 15:30

import atila.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0005_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.CharField(default=atila.utils.random_string, max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('calendar_url', models.URLField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='userprofile.userprofile')),
            ],
        ),
    ]
