# Generated by Django 4.1.4 on 2025-02-17 19:58

import atila.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_serviceprovider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='id',
            field=models.CharField(default=atila.utils.random_code, max_length=32, primary_key=True, serialize=False),
        ),
    ]
