# Generated by Django 4.1.4 on 2025-02-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_serviceprovider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='calendar_url',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cal_com_api_key',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='event_type_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
