# Generated by Django 4.1.4 on 2025-02-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_serviceprovider_calendar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='event_type_id',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cal_com_event_type_slug',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='cal_com_username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
