# Generated by Django 4.1.4 on 2025-02-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_serviceprovider_event_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='cal_com_event_type_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
