# Generated by Django 4.1.4 on 2025-02-17 22:08

import atila.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_serviceprovider_cal_com_event_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.CharField(default=atila.utils.random_code, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1905123456'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
