# Generated by Django 4.1.4 on 2025-02-18 15:07

import atila.utils
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_serviceclient_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.CharField(default=atila.utils.random_code, max_length=32, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.serviceclient')),
                ('provider', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.serviceprovider')),
            ],
        ),
    ]
