# Generated by Django 4.1.4 on 2025-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_servicebooking_deposit_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
