# Generated by Django 4.1.4 on 2025-02-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_alter_servicebooking_deposit_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='booking_uid',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
