# Generated by Django 4.1.4 on 2025-02-18 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_servicebooking_booking_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.serviceclient'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.serviceprovider'),
        ),
    ]
