# Generated by Django 4.1.4 on 2025-02-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_alter_servicebooking_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='cal_com_event_type_slug',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='cal_com_username',
        ),
    ]
