# Generated by Django 4.1.4 on 2025-02-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_remove_serviceprovider_cal_com_event_type_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers', to='chatbot.serviceclient'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='cal_com_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='cal_com_event_type_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
