# Generated by Django 4.1.4 on 2023-01-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='atlas_searches_made',
            new_name='atlas_searches',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='atlas_transcriptions',
            field=models.IntegerField(default=0),
        ),
    ]
