# Generated by Django 4.1.4 on 2024-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_atlas_searches_custom_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='atlas_searches',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='atlas_searches_custom_limit',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='atlas_credits',
            field=models.IntegerField(default=20),
        ),
    ]
